### ISSUE TITLE
Docs about flakehell baseline are misleading 

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1095]
# Bug report

## What's wrong

Docs about `flakehell` misses the configuration part for `pyproject.toml` as stated in https://github.com/cherrypy/cheroot/issues/253#issuecomment-569452946 

Problematic page: https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/flakehell.html

It misses `[tool.flakehell.plugins]` part.

## How is that should be

We need to fix that: our docs should have all the required steps to get started.

**Comment by sobolevn** [comment]
CC @orsinium

**Comment by orsinium** [comment]
I think the best option is to make default flakehell config in [styles](https://github.com/wemake-services/wemake-python-styleguide/tree/master/styles) and use it as [base config](https://flakehell.readthedocs.io/config.html#base):

```toml
[tool.flakehell]
base = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/flakehell.toml"
```

The motivation is wemake has a lot of dependent plugins that have to be explicitly specified for flakehell:

```
[tool.flakehell.plugins]
wemake-python-styleguide = ["+*"]
flake8-builtins = ["+*"]
...
```
