### ISSUE TITLE
Discrepancy between isort and flake8 line length settings

### ISSUE THREAD

**Issue by radzak** [wemake-services/wemake-python-styleguide#1308]
I have a question about the configuration for [nitpick](https://pypi.org/project/nitpick/). Why is the line length different for flake8 and isort?

```toml
["setup.cfg".flake8]
max-line-length = 80

["setup.cfg".isort]
line_length = 79
```

`isort --help`
>   -w LINE_LENGTH, --line-width LINE_LENGTH
                        The max length of an import line (used for wrapping
                        long imports).

`flake8 --help`
>   --max-line-length=n   Maximum allowed line length for the entirety of this
                        run. (Default: 79)

If you're changing the default for flake from 79 to 80, why not do the same for isort?
