### ISSUE TITLE
setup.cfg ignored when using GitHub action in subfolder

### ISSUE THREAD

**Issue by edmondop** [wemake-services/wemake-python-styleguide#2474]
### What's wrong

When you have a multi-module repo, you might have your Python code located in a subfolder, together with its setup.cfg.

Now, you are tempted to use this syntax

```
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.16.1
      with:
        reporter: 'github-pr-check'
        path: './my_subfolder/my_subfolder_2'
```

However the setup.cfg in my_subfolder_2 is ignored

### How it should be

You should not copy the setup.cfg within the working dir

### Flake8 version and plugins

0.16.1 github action

### pip information

?

### OS information

?
