### ISSUE TITLE
Gihub Action: Unable to process file command 'output' successfully.

### ISSUE THREAD

**Issue by zakkg3** [wemake-services/wemake-python-styleguide#2734]
### What's wrong

pipeline fails with "Unable to process file command 'output' successfully."

maybe is relatad with:
> Recently github [has announced change](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) that echo "::set-output name=x::y" command is deprecated and should be replaced by echo "x=y" >> $GITHUB_OUTPUT

### How it should be

print output and not fail.

### Flake8 version and plugins

Github action: https://github.com/zakkg3/ClusterSecret/actions/runs/6107692637/job/16575222161
Here is the action workflow file:

```yaml            
name: Linter
on:
  push:
    branches:
      - '*'
jobs:
  lint:
    name: LinterMonkey
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: GitCheckout

      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
        with:
          reporter: 'github-pr-review'
          path: './src'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
```

### pip information

does not apply

### OS information

ubuntu-latest (see wrokflow file)

**Comment by zakkg3** [comment]
a workaround:

```
name: LinterMonkey
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
      - name: WemakeLint
        run: |
          flake8 ./src
   ```
