### ISSUE TITLE
Exclude Enum classes from the rule WPS115

### ISSUE THREAD

**Issue by gimntut** [wemake-services/wemake-python-styleguide#3238]
### What's wrong

Attributes of Enum classes are usually written in UPPER_CASE. This is not an error, but the WPS115 rule says otherwise.

### How it should be

The WPS115 rule should apply to all classes except those inherited from Enum.

### Flake8 version and plugins
```yaml
platform:
  python_implementation: CPython
  python_version: 3.13.0
  system: Linux
plugins:
- plugin: mccabe
  version: 0.7.0
- plugin: pycodestyle
  version: 2.12.1
- plugin: pyflakes
  version: 3.2.0
- plugin: wemake-python-styleguide
  version: 1.0.0
version: 7.1.1
```
### pip information
```
annotated-types==0.7.0
asgiref==3.8.1
attrs==24.3.0
beautifulsoup4==4.12.3
coverage==7.6.10
distro==1.9.0
django==5.1.4
django-cotton==1.5.1
django-extensions==3.2.3
django-htmx==1.21.0
flake8==7.1.1
iniconfig==2.0.0
mccabe==0.7.0
packaging==24.2
pillow==11.0.0
pluggy==1.5.0
pycodestyle==2.12.1
pydantic==2.10.3
pydantic-core==2.27.1
pyflakes==3.2.0
pygments==2.18.0
pytest==8.3.4
pytest-cov==6.0.0
pytest-django==4.9.0
ruff==0.8.2
ruyaml==0.91.0
setuptools==75.6.0
soupsieve==2.6
sqlparse==0.5.2
typing-extensions==4.12.2
wemake-python-styleguide==1.0.0
whitenoise==6.8.2
```

### OS information

WSL Ubuntu_2404.1.66
### uname -a
`Linux iRu-1 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
