### ISSUE TITLE
`pyproject.toml` misses `[build-system]` tag

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#335]
# Bug report

## What's wrong

Our `pyproject.toml` file misses `[build-system]` tag.

## How is that should be

It should contain:

```toml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
