### ISSUE TITLE
Add python3.7 support

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#72]
We should add `python3.7` to the test matrix.
Currently `travis` has issues in supporting it.

```yaml
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

```
